% Generate and clean the 2D target mesh
% 2D target model is generated by Rhino and grasshopper
clc
clear

%% load target shape and inital shape
% load target deployed shape
modelname = 'circle';
path = strcat('/Users/sean/Desktop/Project 2/3D_Bistable_Conformal_Kirigami/Xiaoyuan_bistable_kirigami_unit/Input_model/2D_shape/');
filename_2D = strcat(modelname,'.obj'); % 2D model the node order is different?
obj_2D = readObj(path,filename_2D); % read 2D object, vertices, connectivity

% change the order the nodes in vt the connectivity doesn't match
sorted_uv = vertice_sort(obj_2D.vt,obj_2D.f.v,obj_2D.f.vt);
obj_2D.vt = sorted_uv;

v_mesh = obj_2D.vt;
f_mesh = obj_2D.f.v;
c_mesh = face_center(v_mesh, f_mesh);

%% Calculate the scale factor of mesh
areas_ini = triangle_area_2D(obj_2D.vt, obj_2D.f.v);  % Deprive the area of mesh in 2D
areas_deploy = triangle_area_3D(obj_2D.v, obj_2D.f.v);  % Deprive the area of mesh in 3D

scale_facs = sqrt(areas_ini./areas_deploy); % Calculate the scale factor. Area_3D/Area_2D

%% Overlay the regular triangular grids to envelop mesh surface
% Define the size of triangular grids
edgeLen = 10;  % control the number of grid regarding the length of mmesh instead of length 28
[v_grid, f_grid, c_grid, i_grid, x_grid] = generate_overlay_grid(v_mesh, edgeLen); % Overlay regular triangular grids in a rectangle box
[v_out, f_out, c_out, i_out, x_out, scale_area] = fit_grid(v_grid, f_grid, c_grid, ...
    i_grid, x_grid, v_mesh, f_mesh, scale_facs, edgeLen); % Remove the grids outside the mesh surface

disp("Scale area min: "+num2str(min(scale_area)) +", max: "+num2str(max(scale_area)))

%% Plot the Overlaid grids
figure(); 
hold on;
TR = triangulation(f_mesh, v_mesh);
B  = freeBoundary(TR);   % boundary edges only
patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceColor', '[0.78 0.80 0.88]', 'EdgeColor', [0.7 0.7 0.7],'LineWidth',0.5); % Plot mesh surface
for i = 1:size(B,1)
    plot(v_mesh(B(i,:),1), v_mesh(B(i,:),2), 'Color', [0.5 0.5 0.5], 'LineWidth', 1.5);
end
plotgrid(f_out,v_out)
axis equal;
axis off;
hold off