% Generate and clean the 3D mesh and conformally transformed 2D mesh
% 3D model is generated by Rhino and grasshopper, and 2D mesh is generated
% by BFF using conformal mapping, and we filter the mesh into triangular
% mesh
clc
clear

%% Input the mesh data generated by BFF
modelname = 'quarter_dome';
%path = strcat('/Users/sean/Desktop/PhD/Program/Project_2_Shape_morphing_3D_kirigami/Xiaoyuan_bistable_kirigami_unit/Input_model/Reference_model/',modelname,'/');
path = strcat('/Users/sean/Desktop/Project 2/3D_Bistable_Conformal_Kirigami/Xiaoyuan_bistable_kirigami_unit/Input_model/Reference_model/',modelname,'/');
%path = strcat('/Users/sean/Desktop/Project 2/Mesh/Isotropic_remeshing/',modelname,'/');
%filename_2D = strcat(modelname,'_iso_flat.obj'); % 2D model isotropic
filename_2D = strcat(modelname,'_flat.obj'); % 2D model the node order is different?

%obj_3D = readObj(path,filename_2D); % read 3D object, vertices, connectivity
obj_2D = readObj(path,filename_2D); % read 2D object, vertices, connectivity

% We need to change the order the nodes in vt the connectivity doesn't match
sorted_uv = vertice_sort(obj_2D.vt,obj_2D.f.v,obj_2D.f.vt);
obj_2D.vt = sorted_uv;

v_mesh = obj_2D.vt;
f_mesh = obj_2D.f.v;
c_mesh = face_center(v_mesh, f_mesh);

%% Calculate the scale factor of mesh
areas_2D = triangle_area_2D(obj_2D.vt, obj_2D.f.v);  % Deprive the area of mesh in 2D
areas_3D = triangle_area_3D(obj_2D.v, obj_2D.f.v);  % Deprive the area of mesh in 3D

scale_facs_mesh = sqrt(areas_3D./areas_2D); % Calculate the scale factor. Area_3D/Area_2D

%% Overlay the regular triangular grids to envelop mesh surface
% Define the size of triangular grids
edgeLen = 28;  % control the number of grid regarding the length of mmesh instead of length
[v_grid, f_grid, c_grid, i_grid, x_grid] = generate_overlay_grid(v_mesh, edgeLen); % Overlay regular triangular grids in a rectangle box
[v_out, f_out, c_out, i_out, x_out, scale_area] = fit_grid(v_grid, f_grid, c_grid, ...
    i_grid, x_grid, v_mesh, f_mesh, scale_facs_mesh, edgeLen); % Remove the grids outside the mesh surface

disp("Scale area min: "+num2str(min(scale_area)) +", max: "+num2str(max(scale_area)))

%% Plot the Overlaid grids
figure(); 
hold on;
TR = triangulation(f_mesh, v_mesh);
B  = freeBoundary(TR);   % boundary edges only
patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceColor', '[0.78 0.80 0.88]', 'EdgeColor', [0.7 0.7 0.7],'LineWidth',0.5); % Plot mesh surface
for i = 1:size(B,1)
    plot(v_mesh(B(i,:),1), v_mesh(B(i,:),2), 'Color', [0.5 0.5 0.5], 'LineWidth', 1.5);
end
plotgrid(f_out,v_out)
axis equal;
axis off;
hold off

%% Plot mesh deployment
[vt_mesh, v_mesh] = mesh_deployment(obj_2D);

%% Reparametrization
% Input admissable range
load("Inverse_design/anisotropy_filter_refine.mat")
mask = (anisotropy_filter_refine.eta_val>0.10) & isfinite(anisotropy_filter_refine.eps_bist);
anisotropy_filter = anisotropy_filter_refine(mask,:);

% Reparaterization based on the admissable range
opts = struct();
[v_initial, v_repa, max_ang, v_target0] = reparameterization(v_out, f_out, vt_mesh, v_mesh, f_mesh);

scale_facs_repa = calculate_scale_facs(v_initial, v_repa, f_out);
min_scale_factor = min(scale_facs_repa(:));
max_scale_factor = max(scale_facs_repa(:));

% Rescale target edges
rescale_factor = 1.20/min_scale_factor;
[v_target, scale_facs, ~] = rescale_target_edges(v_initial, f_out, obj_2D, v_repa, rescale_factor, opts);

lam_min_adm = 1 + min(anisotropy_filter.eps_bist);
lam_max_adm = 1 + max(anisotropy_filter.eps_bist);
disp("Min scale factor: " + num2str(min(scale_facs(:))) + ...
     ", Max scale factor: " + num2str(max(scale_facs(:))) + ...
     " | admissible [" + num2str(lam_min_adm) + ", " + num2str(lam_max_adm) + "]" + ...
     " | max angle: " + num2str(max_ang));

%% Plot grid deployment
grid_deployment(v_target, v_initial, f_out);

[anisotropy_level, ~] = scale_facs_to_angles(scale_facs);

% Visulalize the scale factor on edges
plot_edge_stretch(scale_facs, v_initial, f_out)

% Colourmap scale factor on edges
plot_edge_scale_factors(v_target, f_out, scale_facs)

%% Plot tessellation deployment
% Define the size of tessellation
l1 = edgeLen * 0.85;
l4 = edgeLen * 0.05; % the length of the filament 0.1
t_min = edgeLen * 0.015; % minimum ligament thickness
t_max = edgeLen * 0.020;  % maximum ligament thickness
t  = t_min; % default ligament thickness stored in params
%beta = zeros(size(i_out)); % tilting angle initial
params = [edgeLen % The length of a unit
    l1            % The length of flanks
    l4            % The thickness of flanks         
    t             % The thickness of ligaments
    ];

% Find optimal beta for each unit based on anisotropy_level
[opt_beta, bistability, ~] = assign_opt_beta(anisotropy_level, anisotropy_filter);
opt_t = assign_thickness(bistability, t_min, t_max);   % thr = 0.4

tessellation = tessellated_triangle_initial(f_out, i_out, params, v_initial, opt_beta, opt_t);
%% Plot the tessellated configuration
%colour = {'white', [206,101,95]/255, [90,174,52]/255, [109,131,250]/255}; % The colour of void, flank, filament, Innertriangle
colour = {'white', [0.9216    0.8863    0.4235
], [ 0.7059    0.9608    0.4118], [0.9216    0.8863    0.4235]};
figure()
hold on
for i = 1:size(f_out,1)
    plot_triangle(tessellation{i},colour);
end
hold off
axis off

% Plot the deployment
tessellation_target = tessellated_triangle(f_out, i_out, params, v_target, opt_beta, opt_t); % Generate closed state of deployed

% tessellation_deployment(tessellation,tessellation_target); % Plot deployment


% %% Calculate the energy
% % Plot selected unit from the tessellation
% i = 88;
% nD = 150;
% Nseg = 8;
% [q1, q2, q3, is_valid, reason] = scale_facs_to_q(scale_facs(i,:), edgeLen);
% [E_sel, alpha_sel] = deform_triangle_anisotropic( ...
%     q1, q2, q3, edgeLen, l1, l4, opt_beta(i), opt_t(i), nD, Nseg, true);
% 
% %% Plot global energy
% [E_total, E_unit, info] = calculate_global_energy(params, opt_beta, opt_t, scale_facs, false);
% alpha = linspace(0, 1, nD);
% 
% % Plot energy curve
% % Normalize axes
% Emax = max(E_total);
% E_norm = E_total ./ max(Emax, eps);   % E / Emax
% xi = 1.0;                             % set your xi here
% x_norm = alpha ./ xi;                 % deployment / xi
% 
% % Plot energy curve
% figure('Color','w');
% hold on; box on;
% plot(x_norm, E_norm, '-', 'Color',[0.85 0.33 0.10], 'LineWidth', 1.5, ...
%     'DisplayName', 'Global energy');
% xlabel('Deployment \xi', 'Interpreter','tex', 'FontSize',20);
% ylabel('E/E_{max}', 'Interpreter','tex', 'FontSize',20);
% set(gca, 'FontName','Times New Roman', 'FontSize',28, 'LineWidth',1.5);
% legend('Location','northwest','Box','off', 'FontSize',28);
% grid off;
% 
% % Rectangle aspect (not square) + margin above 1
% xlim([min(x_norm), max(x_norm)]);
% ylim([0, 1.05]);          % slightly larger than 1
% pbaspect([2.0 1 1]);      % rectangular look


%% Create deployment figure
% generate_gif(tessellation, tessellation_target, modelname);

% Create svg cut pattern for fabrication
generate_svg(tessellation, 'quarter_dome_pattern_less',false, [], 0.15);


% %% Plot the original configurations
% figure()
% patch('Vertices', obj_2D.v, 'Faces', obj_2D.f.v, ...
%       'FaceVertexCData', obj_2D.v(:,3),...
%       'FaceColor', 'interp', 'EdgeColor', 'none');
% axis equal;          % Equal scaling for all axes
% axis off;
% view(3);             % Set default 3D view angle
% camlight;            % Add light source
% lighting gouraud;    % Smooth lighting across surfaces
% 
% figure()
% axis equal
% axis off;
% patch('Vertices', obj_2D.vt, 'Faces', obj_2D.f.v, ...
%     'FaceColor', 'none', 'EdgeColor', 'black'); % Plot 2D figure
% view(3);             % Set default 3D view angle
% camlight;            % Add a light source for better visualization
% material shiny;                % Make the surface shiny (adjustable)
% lighting gouraud;    % Smooth lighting across surfaces
% 
% % %% Plot the Overlaid grids(unfiltered)
% % figure(); 
% % hold on;
% % TR = triangulation(f_mesh, v_mesh);
% % B  = freeBoundary(TR);   % boundary edges only
% % patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceColor', '[0.78 0.80 0.88]', 'EdgeColor', [0.7 0.7 0.7],'LineWidth',0.5); % Plot mesh surface
% % for i = 1:size(B,1)
% %     plot(v_mesh(B(i,:),1), v_mesh(B(i,:),2), 'Color', [0.5 0.5 0.5], 'LineWidth', 1.5);
% % end
% % plotgrid(f_grid,v_grid)
% % axis equal;
% % axis off;
% % hold off
% 
% %% Plot the scale_fac tor colormap of mesh surface
% figure()
% patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceVertexCData', scale_facs_mesh, 'FaceColor', 'flat', 'EdgeColor', 'none');
% colormap summer; 
% c = colorbar; 
% c.FontSize = 18;
% axis equal; 
% axis off
% 
% %% Plot the scale_area colormap of overlaid grips
% figure()
% patch('Vertices', v_out(:,1:2), 'Faces', f_out, 'FaceVertexCData', scale_area, 'FaceColor', 'flat', 'EdgeColor', 'none');
% colormap summer; 
% c = colorbar; 
% c.FontSize = 18;
% axis equal; 
% axis off
