clc
clear

% Input the mesh data generated by BFF
path = '/Users/sean/Desktop/PhD/Program/Project_2_Shape_morphing_3D_kirigami/Xiaoyuan_bistable_kirigami_unit/Input_model/';
filename_3D = 'hemisphere.obj'; % 3D model
filename_2D = 'hemisphere_2D.obj'; % 2D model

obj_3D = readObj(path,filename_3D); % read 3D object
obj_2D = readObj(path,filename_2D); % read 2D object

vertices = obj_2D.vt;
faces = obj_2D.f.vt;
edgeLen = 10;
% Deprive the area triangular mesh
areas_2D = triangle_area_2D(obj_2D.vt, obj_2D.f.vt);  % Deprive the area of mesh in 2D
areas_3D = triangle_area_3D(obj_3D.v, obj_3D.f.v);  % Deprive the area of mesh in 3D

% Calculate the stretch factor
scale_facs = areas_3D./areas_2D;

[v_grid, f_grid, c_grid, i_grid, x_grid] = generate_overlay_grid(vertices, edgeLen);
uv_c = face_center(vertices,faces); % find the centroids of triangular mesh
grid_points = c_grid(:,[1,2]);

% check grid_points where inside the mesh surface
tri = triangulation(faces, vertices); % Define triangulation using given faces 
inside = ~isnan(tri.pointLocation(grid_points)); % Check if points are inside the mesh 

f_grid(~inside, :) = NaN;
c_grid(~inside, :) = NaN;
i_grid(~inside, :) = NaN;
for i = find(~inside)'
    x_grid{i} = NaN;
end

% remove all the NaN
index = ~isnan(f_grid);
c_grid = c_grid(index(:,1),:);
i_grid = i_grid(index(:,1),:);
x_grid = x_grid(index(:,1),:);
f_grid = f_grid(index(:,1),:);


%% Identify "Floppy" Polygons(wrong)
idE = get_floppy_triangles(f_grid); % find the floppy triangle that is detached from other triangles % fix this

[f_grid, idxn] = removeId(f_grid, idE); % Remove floppy polygons (NaN)
c_grid(idxn,:) = NaN;
i_grid(idxn,:) = NaN;
for i = find(idxn)'
    x_grid{i} = NaN;
end

% Remove all the NaN
index = ~isnan(f_grid);
c_grid = c_grid(index(:,1),:);
i_grid = i_grid(index(:,1),:);
x_grid = x_grid(index(:,1),:);
f_grid = f_grid(index(:,1),:);

% Iterate over each element of x_grid (each cell represents a list of neighboring faces)
for xi = 1:numel(x_grid)
    current_neighbors = x_grid{xi};
    updated_neighbors = current_neighbors(~ismember(current_neighbors, idxn));
    x_grid{xi} = updated_neighbors;
end

%% Calculate Scale Factors Using Weighted Averaging
scale_area = zeros(size(c_grid,1),1);

for ci_idx = 1:size(c_grid,1)
    beta = 0.5;
    neighbors_idx = pointCloudClosestPoints(uv_c, c_grid(ci_idx,1:2), beta * edgeLen); 
    weights = normalizeWeights(...
    -1/(beta*edgeLen) * vecnorm(c_grid(ci_idx,1:2) - uv_c(neighbors_idx,1:2), 2, 2) + 1 ...
);
    scale_area(ci_idx) = sum(scale_facs(neighbors_idx) .* weights); % Weighted average of scale factors
end

%% Final Adjustments and Output Preparation
v_out = v_grid; % Vertex coordinates remain unchanged
f_out = f_grid; % Face connectivity remains unchanged
c_out = c_grid; % Centroids remain unchanged after filtering invalid entries
i_out = i_grid; % Orientation remains unchanged after filtering invalid entries
x_out = x_grid; % Neighboring relationships remain unchanged after filtering invalid entries

[v_out, f_out] = remove_unused_verts(v_out, f_out); 

grid_points_inside = grid_points(inside,:);
% % Plot the results
% figure; hold on;
% %patch('Vertices', vertices, 'Faces', faces, 'FaceColor', 'none', 'EdgeColor', 'b'); % Plot 2D figure
% patch('Vertices', v_grid, 'Faces', f_grid, 'FaceColor', 'none', 'EdgeColor', 'b'); % Plot 2D figure
% %patch('Vertices', v_out(:,1:2), 'Faces', f_out, 'FaceColor', 'none', 'EdgeColor', 'b'); % Plot 2D figure
% scatter(grid_points_inside(:,1), grid_points_inside(:,2), 'g', 'filled'); % Inside points
% scatter(grid_points(~inside,1), grid_points(~inside,2), 'r', 'filled'); % Outside points
% scatter(uv_c(:,1), uv_c(:,2), 'r', 'filled');
% axis equal; grid off;
% title('Check whether grids inside mesh');
% hold off;
% Loop through each face to place the face number at its centroid
figure;
patch('Vertices', v_grid, 'Faces', f_grid, 'FaceColor', 'none', 'EdgeColor', 'b'); % Plot 2D figure
hold on;
for i = 1:size(f_grid, 1)
    % Place the face number at the centroid
    text(c_grid(i,1), c_grid(i,2), num2str(i), 'Color', 'red', 'FontSize', 10, 'HorizontalAlignment', 'center');
end

% Adjust plot settings
axis equal;