% Generate and clean the 3D mesh and conformally transformed 2D mesh
% 3D model is generated by Rhino and grasshopper, and 2D mesh is generated
% by BFF using conformal mapping, and we filter the mesh into triangular
% mesh
clc
clear

%% Input the mesh data generated by BFF
path = '/Users/sean/Desktop/PhD/Program/Project_2_Shape_morphing_3D_kirigami/Xiaoyuan_bistable_kirigami_unit/Input_model/';
filename_3D = 'hemisphere.obj'; % 3D model
filename_2D = 'hemisphere_2D.obj'; % 2D model

obj_3D = readObj(path,filename_2D); % read 3D object
obj_2D = readObj(path,filename_2D); % read 2D object

% We need to change the order the nodes in vt. the connectivity doesn't match
sorted_uv = vertice_sort(obj_2D.vt,obj_2D.f.v,obj_2D.f.vt);
obj_2D.vt = sorted_uv;

v_mesh = obj_2D.vt;
f_mesh = obj_2D.f.v;
c_mesh = face_center(v_mesh, f_mesh);

%% Calculate the scale factor of mesh
areas_2D = triangle_area_2D(obj_2D.vt, obj_2D.f.v);  % Deprive the area of mesh in 2D
areas_3D = triangle_area_3D(obj_2D.v, obj_2D.f.v);  % Deprive the area of mesh in 3D

scale_facs = areas_3D./areas_2D; % Calculate the scale factor. Area_3D/Area_2D
% for a bistable unit the range of scale factor should be within(1.15,1.75)
disp("Scale facs min: "+num2str(min(scale_facs)) +", max: "+num2str(max(scale_facs)))

%% Overlay the regular triangular grids to envelop mesh surface
edgeLen = 20; % Define the size of triangular grids
[v_grid, f_grid, c_grid, i_grid, x_grid] = generate_overlay_grid(v_mesh, edgeLen); % Overlay regular triangular grids in a rectangle box
[v_out, f_out, c_out, i_out, x_out, scale_area] = fit_grid(v_grid, f_grid, c_grid, ...
    i_grid, x_grid, v_mesh, f_mesh, scale_facs, edgeLen); % Remove the grids outside the mesh surface

%% Tessellate the triangular units with bistable units
tessellation = tessellated_triangle(f_out, c_out, i_out, edgeLen); % Tessellate bistable triangle into fitted grids

%% Plot the results
% Plot the configurations
figure()
patch('Vertices', obj_3D.v, 'Faces', obj_2D.f.v, ...
      'FaceVertexCData', obj_3D.v(:,3),...
      'FaceColor', 'interp', 'EdgeColor', 'none');
axis equal;          % Equal scaling for all axes
axis off;
view(3);             % Set default 3D view angle
camlight;            % Add light source
lighting gouraud;    % Smooth lighting across surfaces

figure()
axis equal
axis off;
patch('Vertices', obj_2D.vt, 'Faces', obj_2D.f.v, ...
    'FaceColor', 'none', 'EdgeColor', 'black'); % Plot 2D figure
view(3);             % Set default 3D view angle
camlight;            % Add a light source for better visualization
material shiny;                % Make the surface shiny (adjustable)
lighting gouraud;    % Smooth lighting across surfaces

% Plot the Overlaid grids
figure(); 
hold on;
patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceColor', 'none', 'EdgeColor', 'black','LineWidth',0.5); % Plot mesh surface
patch('Vertices', v_out(:,1:2), 'Faces', f_out, 'FaceColor', 'none', 'EdgeColor', 'b','LineWidth',1); % Plot overlaid surface
axis equal;
axis off;
hold off

% Plot the scale_factor colormap of mesh surface
figure()
patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceVertexCData', scale_facs, 'FaceColor', 'flat', 'EdgeColor', 'none');
colormap summer; 
c = colorbar; 
c.FontSize = 18;
axis equal; 
axis off

% Plot the scale_area colormap of overlaid grips
figure()
patch('Vertices', v_out(:,1:2), 'Faces', f_out, 'FaceVertexCData', scale_area, 'FaceColor', 'flat', 'EdgeColor', 'none');
colormap summer; 
c = colorbar; 
c.FontSize = 18;
axis equal; 
axis off

% Plot the tessellated configuration
colour = {'white', [206,101,95]/255, [90,174,52]/255, [109,131,250]/255}; % The colour of void, flank, filament, Innertriangle
figure()
hold on
for i = 1:size(f_out,1)
    plot_triangle(tessellation{i},colour);
end
hold off
axis off

% Plot mesh deployment
mesh_deployment(obj_2D);

% Plot grid deployment
[T,v_target] = grid_deployment(obj_2D,c_mesh,v_out,f_out);

% Plot tessellation deployment
tessellation_deployment(tessellation,v_out,v_target,f_out,T);

