% Generate and clean the 3D mesh and conformally transformed 2D mesh
% 3D model is generated by Rhino and grasshopper, and 2D mesh is generated
% by BFF using conformal mapping, and we filter the mesh into triangular
% mesh
clc
clear

%% Input the mesh data generated by BFF
modelname = 'arbitrary_surface';
%path = strcat('/Users/sean/Desktop/PhD/Program/Project_2_Shape_morphing_3D_kirigami/Xiaoyuan_bistable_kirigami_unit/Input_model/Reference_model/',modelname,'/');
path = strcat('/Users/sean/Desktop/Project 2/3D_Bistable_Conformal_Kirigami/Xiaoyuan_bistable_kirigami_unit/Input_model/Reference_model/',modelname,'/');
%path = strcat('/Users/sean/Desktop/Project 2/Mesh/Isotropic_remeshing/',modelname,'/');
%filename_2D = strcat(modelname,'_iso_flat.obj'); % 2D model isotropic
filename_2D = strcat(modelname,'_flat.obj'); % 2D model the node order is different?

%obj_3D = readObj(path,filename_2D); % read 3D object, vertices, connectivity
obj_2D = readObj(path,filename_2D); % read 2D object, vertices, connectivity

% We need to change the order the nodes in vt the connectivity doesn't match
sorted_uv = vertice_sort(obj_2D.vt,obj_2D.f.v,obj_2D.f.vt);
obj_2D.vt = sorted_uv;

v_mesh = obj_2D.vt;
f_mesh = obj_2D.f.v;
c_mesh = face_center(v_mesh, f_mesh);

%% Calculate the scale factor of mesh
areas_2D = triangle_area_2D(obj_2D.vt, obj_2D.f.v);  % Deprive the area of mesh in 2D
areas_3D = triangle_area_3D(obj_2D.v, obj_2D.f.v);  % Deprive the area of mesh in 3D

scale_facs = sqrt(areas_3D./areas_2D); % Calculate the scale factor. Area_3D/Area_2D

%% Overlay the regular triangular grids to envelop mesh surface
% Define the size of triangular grids
edgeLen = 30;  % control the number of grid regarding the length of mmesh instead of length
[v_grid, f_grid, c_grid, i_grid, x_grid] = generate_overlay_grid(v_mesh, edgeLen); % Overlay regular triangular grids in a rectangle box
[v_out, f_out, c_out, i_out, x_out, scale_area] = fit_grid(v_grid, f_grid, c_grid, ...
    i_grid, x_grid, v_mesh, f_mesh, scale_facs, edgeLen); % Remove the grids outside the mesh surface

disp("Scale area min: "+num2str(min(scale_area)) +", max: "+num2str(max(scale_area)))

%% Plot the original configurations
figure()
patch('Vertices', obj_2D.v, 'Faces', obj_2D.f.v, ...
      'FaceVertexCData', obj_2D.v(:,3),...
      'FaceColor', 'interp', 'EdgeColor', 'none');
axis equal;          % Equal scaling for all axes
axis off;
view(3);             % Set default 3D view angle
camlight;            % Add light source
lighting gouraud;    % Smooth lighting across surfaces

figure()
axis equal
axis off;
patch('Vertices', obj_2D.vt, 'Faces', obj_2D.f.v, ...
    'FaceColor', 'none', 'EdgeColor', 'black'); % Plot 2D figure
view(3);             % Set default 3D view angle
camlight;            % Add a light source for better visualization
material shiny;                % Make the surface shiny (adjustable)
lighting gouraud;    % Smooth lighting across surfaces

% %% Plot the Overlaid grids(unfiltered)
% figure(); 
% hold on;
% TR = triangulation(f_mesh, v_mesh);
% B  = freeBoundary(TR);   % boundary edges only
% patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceColor', '[0.78 0.80 0.88]', 'EdgeColor', [0.7 0.7 0.7],'LineWidth',0.5); % Plot mesh surface
% for i = 1:size(B,1)
%     plot(v_mesh(B(i,:),1), v_mesh(B(i,:),2), 'Color', [0.5 0.5 0.5], 'LineWidth', 1.5);
% end
% plotgrid(f_grid,v_grid)
% axis equal;
% axis off;
% hold off

%% Plot the Overlaid grids
figure(); 
hold on;
TR = triangulation(f_mesh, v_mesh);
B  = freeBoundary(TR);   % boundary edges only
patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceColor', '[0.78 0.80 0.88]', 'EdgeColor', [0.7 0.7 0.7],'LineWidth',0.5); % Plot mesh surface
for i = 1:size(B,1)
    plot(v_mesh(B(i,:),1), v_mesh(B(i,:),2), 'Color', [0.5 0.5 0.5], 'LineWidth', 1.5);
end
plotgrid(f_out,v_out)
axis equal;
axis off;
hold off

%% Plot the scale_factor colormap of mesh surface
figure()
patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceVertexCData', scale_facs, 'FaceColor', 'flat', 'EdgeColor', 'none');
colormap summer; 
c = colorbar; 
c.FontSize = 18;
axis equal; 
axis off

%% Plot the scale_area colormap of overlaid grips
figure()
patch('Vertices', v_out(:,1:2), 'Faces', f_out, 'FaceVertexCData', scale_area, 'FaceColor', 'flat', 'EdgeColor', 'none');
colormap summer; 
c = colorbar; 
c.FontSize = 18;
axis equal; 
axis off


%% Plot mesh deployment
mesh_deployment(obj_2D);

%% Plot grid deployment
[T,v_target,v_out] = grid_deployment(obj_2D,c_mesh,v_out,f_out); % Here we need to move and rotate the 3D surface coresponding to 2D surface

%% Reparametrization v_target to fit the boundary(optional)
[v_target, info] = reparameterization(v_out, f_out, obj_2D, v_target, 1.7/1.1, 1.3963);

%% Recalculate scale factor on each edge
% Calculate edge-wise scale factors based on flattened/deployed grids
% scale_facs is Mx3: [edge(n1,n2), edge(n2,n3), edge(n3,n1)] per triangle
scale_facs = calculate_scale_facs(v_out, v_target, f_out);
rescale_facs = 1.1 ./ min(scale_facs(:));
scale_facs = scale_facs * rescale_facs;
disp("Stretch factor min: "+num2str(min(scale_facs(:))) +", max: "+num2str(max(scale_facs(:))))

if max(scale_facs(:)) > 1.65
    disp("Warning: The stretch factors are out of range")
end

[anisotropy_level, ~] = scale_facs_to_angles(scale_facs);

% % Visulalize the scale factor on the edge
plot_edge_stretch(scale_facs, v_out, f_out)

%% Plot tessellation deployment
% Define the size of tessellation
l1 = edgeLen * 0.85;
l4 = edgeLen * 0.05;
t  = edgeLen * 0.015;
beta = zeros(size(i_out)); % tilting angle
params = [edgeLen % The length of a unit
    l1            % The length of flanks
    l4            % The thickness of flanks         
    t             % The thickness of ligaments
    ];
tessellation = tessellated_triangle(f_out, i_out, params,v_out,beta); % Tessellate bistable triangle into fitted grids

%Plot the tessellated configuration
%colour = {'white', [206,101,95]/255, [90,174,52]/255, [109,131,250]/255}; % The colour of void, flank, filament, Innertriangle
colour = {'white', [0.9216    0.8863    0.4235
], [ 0.7059    0.9608    0.4118], [0.9216    0.8863    0.4235]};
figure()
hold on
for i = 1:size(f_out,1)
    plot_triangle(tessellation{i},colour);
end
hold off
axis off

def_facs = def_factor(v_out,v_target,f_out);

v_target = v_target * rescale_facs;

% Plot the deployment
tessellation_target = tessellated_triangle(f_out, i_out, params, v_target, beta); % Generate closed state of deployed

tessellation_deployment(tessellation,tessellation_target); % Plot deployment
