% Generate and clean the 3D mesh and conformally transformed 2D mesh
% 3D model is generated by Rhino and grasshopper, and 2D mesh is generated
% by BFF using conformal mapping, and we filter the mesh into triangular
% mesh
clc
clear

%% Input the mesh data generated by BFF
modelname = 'hemisphere';
path = strcat('/Users/sean/Desktop/PhD/Program/Project_2_Shape_morphing_3D_kirigami/Xiaoyuan_bistable_kirigami_unit/Input_model/Reference_model/',modelname,'/');
filename_3D = strcat(modelname,'.obj'); % 3D model
filename_2D = strcat(modelname,'_flat.obj'); % 2D model

%obj_3D = readObj(path,filename_2D); % read 3D object, vertices, connectivity
obj_2D = readObj(path,filename_2D); % read 2D object, vertices, connectivity

% We need to change the order the nodes in vt the connectivity doesn't match
sorted_uv = vertice_sort(obj_2D.vt,obj_2D.f.v,obj_2D.f.vt);
obj_2D.vt = sorted_uv;

v_mesh = obj_2D.vt;
f_mesh = obj_2D.f.v;
c_mesh = face_center(v_mesh, f_mesh);

%% Calculate the scale factor of mesh
areas_2D = triangle_area_2D(obj_2D.vt, obj_2D.f.v);  % Deprive the area of mesh in 2D
areas_3D = triangle_area_3D(obj_2D.v, obj_2D.f.v);  % Deprive the area of mesh in 3D

scale_facs = areas_3D./areas_2D; % Calculate the scale factor. Area_3D/Area_2D

%% Overlay the regular triangular grids to envelop mesh surface
% Define the size of triangular grids
edgeLen = 15; 
[v_grid, f_grid, c_grid, i_grid, x_grid] = generate_overlay_grid(v_mesh, edgeLen); % Overlay regular triangular grids in a rectangle box
[v_out, f_out, c_out, i_out, x_out, scale_area] = fit_grid(v_grid, f_grid, c_grid, ...
    i_grid, x_grid, v_mesh, f_mesh, scale_facs, edgeLen); % Remove the grids outside the mesh surface

disp("Scale area min: "+num2str(min(scale_area)) +", max: "+num2str(max(scale_area)))

%% Tessellate the triangular units with bistable units
% Define the size of tessellation
% edgeLen = l1 + 2*l4 + l2  l4 = (edgeLen - l1 - l2)/2
l1 = edgeLen * 0.8;
l2 = edgeLen * 0.1;
t  = edgeLen * 0.02;
l3 = l1 -2*l2 - (edgeLen - l1 -l2)/2;  % stretch length
params = [edgeLen % The length of a unit
    l1            % The length of flanks
    l2            % The length of ligaments           
    l3            % The length of innertriangles
    t             % The thickness of ligaments
    ];
tessellation = tessellated_triangle(f_out, i_out, params,v_out); % Tessellate bistable triangle into fitted grids

%% Plot the original configurations
% figure()
% patch('Vertices', obj_2D.v, 'Faces', obj_2D.f.v, ...
%       'FaceVertexCData', obj_2D.v(:,3),...
%       'FaceColor', 'interp', 'EdgeColor', 'none');
% axis equal;          % Equal scaling for all axes
% axis off;
% view(3);             % Set default 3D view angle
% camlight;            % Add light source
% lighting gouraud;    % Smooth lighting across surfaces
% 
% figure()
% axis equal
% axis off;
% patch('Vertices', obj_2D.vt, 'Faces', obj_2D.f.v, ...
%     'FaceColor', 'none', 'EdgeColor', 'black'); % Plot 2D figure
% view(3);             % Set default 3D view angle
% camlight;            % Add a light source for better visualization
% material shiny;                % Make the surface shiny (adjustable)
% lighting gouraud;    % Smooth lighting across surfaces

%% Plot the Overlaid grids
% figure(); 
% hold on;
% patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceColor', 'none', 'EdgeColor', 'black','LineWidth',0.5); % Plot mesh surface
% plotgrid(f_out,v_out)
% axis equal;
% axis off;
% hold off

%% Plot the scale_factor colormap of mesh surface
% figure()
% patch('Vertices', v_mesh, 'Faces', f_mesh, 'FaceVertexCData', scale_facs, 'FaceColor', 'flat', 'EdgeColor', 'none');
% colormap summer; 
% c = colorbar; 
% c.FontSize = 18;
% axis equal; 
% axis off

%% Plot the scale_area colormap of overlaid grips
% figure()
% patch('Vertices', v_out(:,1:2), 'Faces', f_out, 'FaceVertexCData', scale_area, 'FaceColor', 'flat', 'EdgeColor', 'none');
% colormap summer; 
% c = colorbar; 
% c.FontSize = 18;
% axis equal; 
% axis off

%% Plot the tessellated configuration
colour = {'white', [206,101,95]/255, [90,174,52]/255, [109,131,250]/255}; % The colour of void, flank, filament, Innertriangle
figure()
hold on
for i = 1:size(f_out,1)
    plot_triangle(tessellation{i},colour);
end
hold off
axis off

%% Plot mesh deployment
mesh_deployment(obj_2D,modelname);

%% Plot grid deployment
[T,v_target] = grid_deployment(obj_2D,c_mesh,v_out,f_out,modelname); % Here we need to move and rotate the 3D surface coresponding to 2D surface

%% Plot tessellation deployment
% Calculate stretch facor based on flattened grid and deployed grid
% for a bistable unit the range of stretch factor should be within(1.15,1.75)
areas_2D = triangle_area_2D(v_out, f_out);  % Deprive the area of grid in 2D
areas_3D = triangle_area_3D(v_target, f_out);  % Deprive the area of grid in 3D

scale_facs = areas_3D./areas_2D; % Calculate the scale factor. Area_3D/Area_2D
stretch_facs = sqrt(scale_facs);
rescale_facs = 1.1/min(stretch_facs);

stretch_facs = stretch_facs * rescale_facs;
disp("Stretch factor min: "+num2str(min(stretch_facs)) +", max: "+num2str(max(stretch_facs)))

if min(min(stretch_facs)) < 0.95 || max(max(stretch_facs)) > 1.75
    disp("Warning: The stretch factors are out of range")
end

% Calculate the stretch facor based on every edge(every edge deploy
% differently)
def_facs = def_factor(v_out,v_target,f_out);

v_target = v_target * rescale_facs;

tessellation_target = tessellated_triangle(f_out, i_out, params, v_target); % Generate closed state of deployed

% Define parameters
tessellation_deployment(tessellation,tessellation_target,T,modelname); % Plot deployment